version: 2
machine:
  pre:
    - sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
jobs:
  front:
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      TARGET: "front"
    steps:
      - checkout
      - run: bash test.sh

  back:
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      TARGET: "back"
    steps:
      - checkout
      - run: bash test.sh

workflows:
  version: 2
  build:
    jobs:
      - back
      - front
