version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1

    steps:
      - checkout

  front:
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      TARGET: "front"
    steps:
      - run: bash test.sh

  back:
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      TARGET: "back"
    steps:
      - run: bash test.sh

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - back:
          requires:
            - build
      - front:
          requires:
            - build
